CS512 - Computer Vision - Assignment 0

Submitted by-

Tushar Gwal
A20449419

In [21]:
#Necesary libraries for operations
import numpy as np
from random import randint, uniform,random
import math
import sympy as sp


# Part A: Vector Operations

In [35]:
# Lets define the given vectors
p = np.array([2, -1, 4])
q = np.array([0, 3, 5])
r = np.array([1, -2, 2])

# 1. 3p+2q
r1 = 3 * p + 2 * q
print("1. 3p+2q =", r1)

# 2. p^: a unit vector in the direction of p
p_u = p / np.linalg.norm(p)
print("2. p^ =", p_u)

# 3. |p| and the angle of p relative to the positive y-axis
p_n = np.linalg.norm(p)
angle_y = np.arccos(p[1] / p_n)
print("3. |p| =", p_n)
print("3. Angle of p relative to the positive y-axis =", np.degrees(angle_y), "degrees")

# 4. The direction cosines of p
direction_cosines = p / p_n
print("4. Direction cosines of p =", direction_cosines)

# 5. The angle between p and q
pq = np.dot(p, q)
angle_pq = np.arccos(pq / (np.linalg.norm(p) * np.linalg.norm(q)))
print("5. Angle between p and q =", np.degrees(angle_pq), "degrees")

# 6. p.q and q.p
pq = np.dot(p, q)
qp = np.dot(q, p)
print("6. p.q =", pq)
print("6. q.p =", qp)

# 7. p.q using the angle between p and q
pq_angle = np.linalg.norm(p) * np.linalg.norm(q) * np.cos(angle_pq)
print("7. p.q using the angle between p and q =", pq_angle)

# 8. The scalar projection of q onto p^
projection = np.dot(q, p_u)
print("8. Scalar projection of q onto p^ =", projection)

# 9. A vector that is perpendicular to p
perpendicular = np.cross(p, np.array([1, 0, 0]))
print("9. Vector perpendicular to p =", perpendicular)

# 10. p x q and q x p
pxq = np.cross(p, q)
qxq = np.cross(q, p)
print("10. p x q =", pxq)
print("10. q x p =", qxq)

# 11. A vector that is perpendicular to both p and q
perpendicular_both = np.cross(p, q)
print("11. Vector perpendicular to both p and q =", perpendicular_both)

# 12. The linear dependency between p, q, and r
mat = np.array([p, q, r]).T
det = np.linalg.det(mat)
if det != 0:
    print("12. p, q, and r are not linearly independent")
else:
    print("12. p, q, and r are linearly dependent")

# 13. Ptq and pqt (here t is transpose)

p = np.array([2, -1, 4])
q = np.array([0, 3, 5])

pqt = np.outer(p, q)
ptq = np.dot(p.T, q)

print("p.q^T =", pqt)
print("p^T.q =", ptq)

1. 3p+2q = [ 6  3 22]
2. p^ = [ 0.43643578 -0.21821789  0.87287156]
3. |p| = 4.58257569495584
3. Angle of p relative to the positive y-axis = 102.60438264837919 degrees
4. Direction cosines of p = [ 0.43643578 -0.21821789  0.87287156]
5. Angle between p and q = 50.490287713806076 degrees
6. p.q = 17
6. q.p = 17
7. p.q using the angle between p and q = 17.0
8. Scalar projection of q onto p^ = 3.709704134011871
9. Vector perpendicular to p = [0 4 1]
10. p x q = [-17 -10   6]
10. q x p = [17 10 -6]
11. Vector perpendicular to both p and q = [-17 -10   6]
12. p, q, and r are not linearly independent
p.q^T = [[ 0  6 10]
 [ 0 -3 -5]
 [ 0 12 20]]
p^T.q = 17


# Part B: Matrix Operations

In [57]:
# lets  define the given values
X = np.array([[2, 1, 0], [-1, 3, 4], [3, 2, -2]])
Y = np.array([[4, -1, 2], [3, 0, -3], [1, 2, 1]])
Z = np.array([[2, 0, -1], [1, 4, 5], [3, 1, 2]])
S = np.array([-1, 4, 0])

# 1. X + 2Y
r1 = X + 2 * Y
print("1. X + 2Y =\n", r1)

# 2. XY and YX
XY = np.dot(X, Y)
YX = np.dot(Y, X)
print("2. XY =\n", XY)
print("   YX =\n", YX)

# 3. |XY|t and YtXt
XY_t = np.transpose(XY)
Y_t_X_t = np.dot(np.transpose(Y), np.transpose(X))
print("3. |XY|t =\n", XY_t)
print("   YtXt =\n", Y_t_X_t)

# 4. |X| and |Z|
det_X = np.linalg.det(X)
det_Z = np.linalg.det(Z)
print("4. |X| =", det_X)
print("   |Z| =", det_Z)

# 5. The matrix (either X, Y, or Z) in which the row vectors form an orthogonal set
#checks if the dot product of each pair of rows is zero, it it is true then the matrix is orthogonal and return value
def is_ortho(mt):
    for i in range(len(mat)):
        for j in range(i + 1, len(mt)):
            if np.dot(mt[i], mt[j]) == 0:
                print("5. Found a matrix: \n", mt)
                print(f" here rows {i+1} and {j+1} are orthogonal.")
                return

is_ortho(X)
is_ortho(Y)
is_ortho(Z)

# 6. x^-1 and Y^-1
if det_X != 0:
    X_inv = np.linalg.inv(X)
    print("6. X^-1 =\n", X_inv)
else:
    print("6. X is not invertible.")
det_Y = np.linalg.det(Y)
if det_Y != 0:
    Y_inv = np.linalg.inv(Y)
    print("   Y^-1 =\n", Y_inv)
else:
    print("   Y is not invertible.")

# 7. Z^-1
if det_Z != 0:
    Z_inv = np.linalg.inv(Z)
    print("7. Z^-1 =\n", Z_inv)
else:
    print("7. Z is not invertible.")

# 8. Xs
XS = np.dot(X, S)
print("8. X s =\n", XS)

# 9. The scalar projection of the rows of X onto the vector s (with s normalized)
S_nmlz = S / np.linalg.norm(S)
scal_p = np.dot(X, S_nmlz)
print("9. Scalar projection of rows of X onto s =\n", scal_p)

# 10. The vector projection of the rows of X onto the vector s (with s normalized)
vec_p = np.outer(scal_p, S_nmlz)
print("10. Vector projection of rows of X onto s =\n", vec_p)

# 11. The linear combination of the columns of X using the elements of s
lin_c = np.dot(X, S)
print("11. Linear combination of columns of X using s =\n", lin_c)

# 12. The solution t for the equation Y t = s
t = np.linalg.solve(Y, S)
print("12. Solution t for Y t = s is \n", t)

# 13. The solution t for the equation Z t = s and the reason for it
if det_Z != 0:
    t = np.linalg.solve(Z, S)
    print("13. Solution t for Z t = s is \n", t)
else:
    print("13. No solution exists for Z t = s because Z is not invertible.")

1. X + 2Y =
 [[10 -1  4]
 [ 5  3 -2]
 [ 5  6  0]]
2. XY =
 [[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
   YX =
 [[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]
3. |XY|t =
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
   YtXt =
 [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
4. |X| = -17.999999999999996
   |Z| = 17.0
5. Found a matrix: 
 [[ 4 -1  2]
 [ 3  0 -3]
 [ 1  2  1]]
 here rows 2 and 3 are orthogonal.
6. X^-1 =
 [[ 0.77777778 -0.11111111 -0.22222222]
 [-0.55555556  0.22222222  0.44444444]
 [ 0.61111111  0.05555556 -0.38888889]]
   Y^-1 =
 [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]
7. Z^-1 =
 [[ 0.17647059 -0.05882353  0.23529412]
 [ 0.76470588  0.41176471 -0.64705882]
 [-0.64705882 -0.11764706  0.47058824]]
8. X s =
 [ 2 13  5]
9. Scalar projection of rows of X onto s =
 [0.48507125 3.15296313 1.21267813]
10. Vector projection of rows of X onto s =
 [[-0.11764706  0.47058824  0.        ]
 [-0.76470588  3.05882353  0.        ]
 [-0.29411765  

# Part C: Eigenvalues and Eigenvectors

1. The eigenvalues and corresponding eigenvectors of M

In [59]:
M = np.array([[3, 2], [-1, 4]])

e_values, e_vectors = np.linalg.eig(M)

print("Eigenvalues of M:", e_values)
print("Eigenvectors of M:", e_vectors)

Eigenvalues of M: [3.5+1.32287566j 3.5-1.32287566j]
Eigenvectors of M: [[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]


2. The dot product between the eigenvectors of M

In [60]:
e_vect1 = e_vectors[:, 0]
e_vect2 = e_vectors[:, 1]

dp = np.dot(e_vect1, e_vect2)
print("Dot product between eigenvectors of M:", dp)

Dot product between eigenvectors of M: (1.0000000000000002+0j)


3. The dot product between the eigenvectors of N

In [62]:
N = np.array([[5, -3], [-3, 6]])

e_values, e_vectors = np.linalg.eig(N)

e_vect1 = e_vectors[:, 0]
e_vect2 = e_vectors[:, 1]

dp = np.dot(e_vect1, e_vect2)
print("Dot product between eigenvectors of N:", dot_product)

Dot product between eigenvectors of N: 17


4. The property of the eigenvectors of N and the reason for it

In [14]:
print("Eigenvectors of N are orthogonal because N is a symmetric matrix.")

Eigenvectors of N are orthogonal because N is a symmetric matrix.


5. The value of a trivial solution t to the equation Pt=0

In [15]:
t_trivial = np.array([0, 0])
print("Trivial solution to Pt=0:", t_trivial)

Trivial solution to Pt=0: [0 0]


6. The value of two non-trivial solutions t to the equation Pt=0

In [19]:
P = sp.Matrix([[2, 4], [4, 8]])

null_space = P.nullspace()
print("Non-trivial solutions to Pt=0:", null_space)

Non-trivial solutions to Pt=0: [Matrix([
[-2],
[ 1]])]


7. The only solution t to the equation M t=0 and the reason for having a single solution

In [17]:
print("The only solution to Mt=0 is t=[0, 0] because M is an invertible matrix.")

The only solution to Mt=0 is t=[0, 0] because M is an invertible matrix.


# Part D: Neural Networks Basics

1. Compute the output of the neuron before applying any activation function

In [73]:
x1 = 0.5
x2 = -0.8
x3 = 0.3
w1 = 0.4
w2 = -0.6
w3 = 0.9
b = 0.2

z = w1 * x1 + w2 * x2 + w3 * x3 + b
print("Output before activation z =", z)

Output before activation z = 1.15


2. Apply the sigmoid activation function

In [75]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

out2 = z  # taken from previous question
act2 = sigmoid(out2)
print("Activation value:", act2)

Activation value: 0.759510916949111


3. Compute the output of the neuron after applying a ReLU activation function

In [76]:
def relu(x):
    return max(0, x)

x1 = 0.5
x2 = -0.8
x3 = 0.3
w1 = 0.4
w2 = -0.6
w3 = 0.9
b = 0.2

out3 = w1 * x1 + w2 * x2 + w3 * x3 + b
act3 = relu(out3)
print("Activation value (ReLU):", act3)

Activation value (ReLU): 1.15


4. Compute the output of the layer using ReLU activation

In [79]:
W = np.array([[0.4, 0.3], [0.2, 0.7]])
b = np.array([0.1, -0.1])
x = np.array([1, 2])

def relu(x):
    return np.maximum(x, 0)

out4 = np.dot(W, x) + b
act4 = relu(out4)
print("Output of the layer (ReLU):", act4)

Output of the layer (ReLU): [1.1 1.5]


5. Compute the output of the layer using sigmoid activation

In [80]:
W = np.array([0.5, -0.3])
b = np.array([0, 1])
x = act4 # taken from previous question

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

out5 = np.dot(W, x) + b
act5 = sigmoid(out5)
print("Output of the layer (sigmoid):", act5)

Output of the layer (sigmoid): [0.52497919 0.75026011]
